# Generated by Django 2.2.11 on 2020-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.CharField(max_length=50)),
                ('Supplier_id', models.CharField(max_length=50)),
                ('Service', models.CharField(max_length=50)),
            ],
        ),
    ]
