# Generated by Django 2.2.11 on 2020-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=50)),
                ('tender_id', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
                ('files', models.CharField(max_length=100)),
                ('online_payment', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('end_date', models.DateField(blank=True)),
                ('update_date', models.DateField(blank=True)),
            ],
        ),
    ]
