# Generated by Django 2.2.11 on 2020-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_auto_20200513_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='files',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tender',
            name='online_payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tender',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tender',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
