# Generated by Django 2.2.11 on 2020-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_auto_20200513_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Count_of_applied',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
