# Generated by Django 2.2.11 on 2020-06-01 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tender_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
