# Generated by Django 2.2.11 on 2020-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_comment_tender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=200),
        ),
    ]
