# Generated by Django 2.2.11 on 2020-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendersOffers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderoffer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
