# Generated by Django 2.2.11 on 2020-05-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendersOffers', '0002_auto_20200512_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderoffer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
