# Generated by Django 2.2.11 on 2020-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendersOffers', '0004_auto_20200512_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderoffer',
            name='tender_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
